### ISSUE TITLE
Use Resource Oriented Design

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1036]
Confirm that we follow REST and resource-centric design, rather than service/operation-centric design.

**Comment by zimeon** [comment]
Suggest changing title to simply "Resource Oriented".

**Comment by zimeon** [comment]
Suggest: _"IIIF specifications should follow resource-centric design principles and use REST interfaces, rather than service or operation-centric design patterns."

**Comment by sdellis** [comment]
Does the naming of REST in this principle prevent the exploration of GraphQL as a web service technology? Facebook and GitHub (among others) have implemented GraphQL for performance benefits (fewer HTTP requests) and ease of long-term endpoint maintenance. It generally seems in line with the principle's intent:

> The intent of adopting this principle is to ensure that the specifications are cacheable and performant, at the same time as being easy to understand and implement.

**Comment by azaroth42** [comment]
Prevent the "exploration" of things? No. The specification of GraphQL as the basis of a new API? Maybe, depends on other factors as below.  The re-specification of the Presentation API as a GraphQL-requiring system: Yes. 

Notably:
  * It's not level 0 compatible. You can't just store things on disk.
  * Caching is problematic when every client wants something slightly different.
  * As simple as possible and no simpler ... GET is simple. GraphQL is not.

GraphQL is good when you have a real, deeply interconnected graph. IIIF does not have this yet.  We spent a lot of time looking at the interaction patterns between client and server in the early days and settled on the collection / manifest / annotation-list separation as the optimal for the 90% case.

**Comment by sdellis** [comment]
If I understand it correctly, the Design Principles are meant to guide the design of all APIs (not just the current Presentation API), now and into the future. If that's the case, then **a "maybe" means that REST should not be specifically called out as a design principle** since there's a possibility that GraphQL could be the basis of a future API. The same thinking applies to the notion of IIIF not having deeply interconnected graphs yet. If we anticipate that one day IIIF will have deeply interconnected graphs, then my point is that the principle should not specify one approach over another that might handle this scenario better. I propose we leave both REST and GraphQL out of the principle statement.

And as an aside, you don't do caching in GraphQL. It's a thin interface that sits on top of other systems (which could include "storing things on disk"), so the GraphQL service layer is not where caching goes.  I also want to point out that we are not comparing GraphQL to GET; we are comparing it to REST, which comes with its own complexities, one of which is maintenance and support over time. I happen to think that GraphQL is quite simple from a client-side perspective. I see my comment on #1041 as this now applies to that principle.

**Comment by zimeon** [comment]
These principles are written in Markdown and not stone. I think that affirming REST is the correct approach for now (and likely a few more years), and caching and level0 should be important considerations given current IIIF use patterns. That may change later but we can cross that bridge when we get there.

**Comment by sdellis** [comment]
@zimeon A "principle" is an enduring truth that is not supposed to change, so effort should be made to get it right the first time. Version our principles defeats the purpose. And again, GraphQL is completely compatible with caching and level0, so I don't see how it's a valid argument for specifically naming REST as a design principle.

**Comment by azaroth42** [comment]
The document states its intent in the first paragraph: a catalog of the principles that have emerged to date, to be used as a guide, to promote consistency.  This is very far from an "enduring truth" so please stop making up problems where they do not exist.

And I disagree that GraphQL is compatible with caching or level0 in any meaningful sense.  As each client can request a different structure at will, the cache would have an extremely low match rate and become very large.  As it's POST where the response changes dependent on the request-body, you can't just put files on disk and have it work.

**Comment by zimeon** [comment]
Proposal from 2017-03-17 community call is to change:

> IIIF specifications follow resource-centric design principles and use REST interfaces, rather than service or operation-centric design patterns. 

to

> IIIF specifications follow resource-centric design principles, for example by using REST interfaces rather than service or operation-centric design patterns.

**Comment by zimeon** [comment]
Change made in http://iiif.io/api/annex/notes/design_patterns/#use-resource-oriented-design
