### ISSUE TITLE
Loosely Couple APIs

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1039]
APIs are loosely coupled rather than bound tightly together.  Can implement Presentation API without Image API and vice versa.  

Note that Search IS bound somewhat to the Presentation API ... but is practically a profile of the w3c annotation protocol ... so just building on standards. [or informing them!]

**Comment by zimeon** [comment]
Suggest: _"Where possible, IIIF APIs should be loosely coupled rather than tightly bound together. This allows independent implementation and tooling, and simplifies the process for API updates. For example, it is possible to implement the IIIF Presentation API without the IIIF Image API and vice versa. As a counter example, the IIIF Search API is necessarily bound somewhat to the IIIF Presentation API."_

**Comment by jpstroop** [comment]
This seems nearly redundant with #1047, or at least I think they could be coupled together. Also brushes up against #1053. Could the three be collapsed, or share a common parent heading?

**Comment by zimeon** [comment]
Agreement on 2017-03-15 community call.
