### ISSUE TITLE
Intelligently Manage Ramping Up

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#1044]
Level 0 is important.  Should be able to implement things as just flat files on disk without complex dynamic systems.  Must not require costly or complicated libraries to get to the basic level.

**Comment by zimeon** [comment]
For all IIIF application areas so far, a level0 solution has been realistic and useful. I'm not sure that will be possible with every direction we might go in, but I think that _where possible_ the minimum viable solution should be implementable as static web resources (e.g. files on disk with simple web hosting).

A very positive side effect of this approach is that simple examples can be hosted on github pages or similar.

**Comment by azaroth42** [comment]
Auth certainly doesn't have a "level 0" implementation! So I agree the language needs to be clearer, but "allow quick implementations with the minimum functionality" is an important point (IMO)

**Comment by zimeon** [comment]
Suggest: _"It is important to support simple and quick implementations as a way to encourage adoption. Where possible, IIIF specifications should allow basic implementation with static web resources ("level 0"). They should not require costly or complicated libraries to get started."_

**Comment by jpstroop** [comment]
+1 to @zimeon's last sentence in particular--we should always aim to to minimize the amount of specialized tooling required to implement the IIIF specifications.

I think this ties into #1048 to some extent as well, and anything else that relates to existing standards, web architecture, etc., but we may not need to make that link explicit if the doc stays short enough.

**Comment by jpstroop** [comment]
And furthermore, we should avoid placing value on one technology (or format, etc) over another unless there is a clear benefit and it does not pose a significant barrier to entry, e.g., it makes sense to call out `jpg` as a level 0 requirement because it is beyond ubiquitous, but even implicitly requiring a jp2 on the server side in order to get to level 2 compliance in the image API would be a Bad Thing (:tm:).

We've done a good job of this to date by abstracting concepts (e.g. we have "scale factors" 1, 2, 4, 8, and 16 not "decomposition levels" 1-5), but it would be great to have a place to point to that explains why that was the approach.

**Comment by azaroth42** [comment]
Splitting @jpstroop's last comment to a new issue.

**Comment by zimeon** [comment]
Agreed on 2017-03-15 community call.
