### ISSUE TITLE
Consider how to do sqrt(2) scale factors

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#447]
Or other non integer factors.

**Comment by zimeon** [comment]
Based on comment from Rod McFarland <https://groups.google.com/forum/?hl=en#!topic/iiif-discuss/8oH_hxIBs5g>:
> 1) Tile Scale Factors: I find the most natural-feeling zooming effect is by using powers of sqrt(2), which translates to 200%, 141%, 100%, 71%, 50%  and so on, but the spec says that the advertised scale factors are expressed as "an integer* by which to divide the full size of the image". If it weren't an integer I might be able to comply. As it is, I just don't list the factors that aren't integers, even though I cache tiles at those scales. Also, is it plausible that a scale factor of, say, 7 would be used? 
 1a) *"positive integer" more pedantically correct

**Comment by zimeon** [comment]
The slightly sarcastic point about whether a scale factor of 7 would be useful bring home to me the slightly odd generalization we have made for scaleFactors: We knew of various tools systems that used integers _n_ to represent _2^n_ scaling. That seemed too tied to a specific use so we generalized to expression of the scale factor itself (rather than the exponent/level).  Is this generalization actually any use except in making the description simpler? Probably not, I bet everyone is using 1,2,4,8,16...

How could we support Rod's request? With an exponent system one could define a level _n_ as representing the scale factor _2^(n/2)_, so then 1,2,3,... would be 100%,71%,50%,... but that is tied to the specific generalization of _sqrt(2)_ scaling. With our current definition we could say that scaleFactors is a positive real number, allowing 1.0,1.41..,2.0,2.82..,4,... In terms of implementation this would not be very hard, but rounding can then mess up caching. I note that extension to allow real would be a non-breaking API change.

Would be great to try to get more input from iiif-discuss about others using/wanting sqrt(2) sacling and/or other factors that can't be expressed now.

**Comment by zimeon** [comment]
Discussion on IIIF Discuss call: 
  * Sean points out experience with a viewer that did multiple rescaling (in server and client) that looked worse than one doing rescaling only in client. This argues against sqrt(2) rescaling on server because image will likely be scaled again.
  * Note that this question is not about the general case of arbitrary rescaling supported through IIIF requests, but about specification of the scale factors that the server supports optimally. 
  * Nobody on call knows of a tool except the one Rob McFraland mentions that uses non-integer scaled tiles
  * Consensus to defer

**Comment by azaroth42** [comment]
Wouldn't it be a breaking change to make the scaleFactors floats rather than integers? In which case we're pushing to 3.0 to re-consider?

**Comment by azaroth42** [comment]
Propose close wontfix

**Comment by jpstroop** [comment]
:+1:

**Comment by zimeon** [comment]
:+1: to close wontfix, we do not have a compelling need/use-case for this

**Comment by tomcrane** [comment]
👍

**Comment by zimeon** [comment]
API review at The Hague, issue stale and without compelling use cases or experimentation. Close wontfix
