### ISSUE TITLE
viewingHint for collections to distinguish curated vs multi-work object role

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#466]
Affects how the display might be presented, e.g. to step from one manifest to the next in a multi-work object rather than simply displaying them in a list for a curated set of distinct objects.

**Comment by azaroth42** [comment]
@tomcrane ...
Can't the multi-volume collection just be a new manifest that includes the same set of canvases?
How would client behavior differ in the collection case?

**Comment by tomcrane** [comment]
Example: http://wellcomelibrary.org/player/b18031511

A six volume work. Each volume needs its own structural information; it is an independent "readable object" with its own covers, TOC and chapters. 

Initially I tried to model this in IIIF as one manifest with six sequences, because we were using one _package_ (in our pre-IIIF silo) per catalogue record. A package is (at first glance) very similar to a manifest, but with one crucial difference - a package has _structures_ that are allocated assetSequences, and an assetSequence has _sections_ that are allocated assets (http://player.digirati.co.uk/data-model.html#domainModel). So volumes/books are structures in the package, and chapters are sections in the assetSequence. The similarity of the names in the model sent me off on the wrong path I think. 

In a IIIF manifest, the structural information is asserted at the manifest level; ranges can be allocated canvases across sequences. There is no separation of structure of sequences and structure of canvases within sequences, because (I think) sequences are not modelling quite the same things I was modelling.

In this model, b18031511 is one _package_ with six _sequences_: http://wellcomelibrary.org/package/b18031511 (the zeroth assetSequence is in this JSON, and the other 5 are referenced right at the end of the file). Each sequence is independently dereferenceable and carries its own structural information about covers, TOC, chapters. In the IIIF Presentation API, while a sequence is obviously dereferenceable, any structural information is lost because it lives in the manifest.

This is where I realised that I can't model it the same way; IIIF sequences are not modelling the same thing as my assetSequence - my interpretation of the IIIF model now is that a manifest models a single "readable object" (a manuscript, or one volume of this six volume work). Attempts to make one manifest per catalogue record will fail if the catalogue record describes multiple independent readable objects (although usually we DO have one catalogue record per readable object). A manifest might have more than one sequence if there are alternative proposed orderings of the canvases, but this example is six discrete books, therefore six manifests. This means that a sequence can't lose its structure when dereferenced; a sequence doesn't need its own independent structure.

So now I do (or intend to do) this:

Step 0 (for people and templates that don't know b18031511 is a multiple volume work):
http://wellcomelibrary.org/iiif/b18031511/manifest

302 Found, redirect:
Step 1
http://wellcomelibrary.org/iiif/collection/b18031511

Step 2 (not implemented yet)
Viewer loads this collection, recognises it as a single logical item (from the proposed viewingHint), and generates a UI similar to http://wellcomelibrary.org/player/b18031511

Compare with a viewer loading http://example.org/iiif/collection/dutch_golden_age
Here (a curated collection) the viewer might generate a thumbnail gallery.

    "Can't the multi-volume collection just be a new manifest that includes the same set of canvases?"

What would this manifest look like for this book?

And then, taking it to extremes:

http://wellcomelibrary.org/player/b19974760
http://wellcomelibrary.org/package/b19974760
http://wellcomelibrary.org/iiif/collection/b19974760 (a work in progress)

This package has 6361 sequences. In the periodicals/newspapers case, one manifest per issue with a hierarchy of collections above it seems sensible. With dates of course!

**Comment by azaroth42** [comment]
Needs proposal...

**Comment by azaroth42** [comment]
Closed with multi-part viewing hint; and added individuals viewing hint for non-multi-part
