### ISSUE TITLE
Clarify and width and height are for calculating an aspect ratio only

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#477]
`width` and `height` and `sizes : [ ]` are redundant.

Should we clarify the use of `width` and `height` as an aspect ratio by renaming to something like `aspect_x`, `asepect_y`. Or maybe even reduce to a single property, `aspect: { " x" : 123, "y" : 456 }`?

size comes from `sizes`.

 * [x] fixed on 2.1.1 branch
 * [ ] merged to master

**Comment by jpstroop** [comment]
Actually, just rely on sizes and get rid of the redundant w/h properties altogether. If the server supports arbitrary sizes the client can calculate the aspect ratio from the largest size.

**Comment by azaroth42** [comment]
Is this agreed upon and scheduled, or discussion deferred until 3.0 ?

**Comment by jpstroop** [comment]
I think we can defer, though it might still be worth discussing f2f during this eds meeting.

**Comment by azaroth42** [comment]
:+1:

**Comment by zimeon** [comment]
I think that `width` and `height` have different and useful meaning separate from the largests size in `"sizes": [ ]`:

  * sizes in `sizes : [ ]` are defined for the client to _request complete images at different sizes that the server has available_ and _should have a region parameter of “full”_ (<http://iiif.io/api/image/2.0/#image-information>) -- the expectation is the ability to get the complete image at these sizes
  * `width` and `height` indicate the maximum size that a zoom viewer should zoom to. Such an image may only be available using tiles of rather smaller size (e.g. imagine I have 10^9 by 10^9 pixel image from Sean's fractal generator of a sky survey than cannot practically be represented as a single full-region image, or an institution does not want to make full-region images at full-resolution to be easily downloadable).

Note that it still would not be appropriate to say `max_width` and `max_height` because implementations may allow scaled-up images to be requests.

Probably the best terminology is `full_width` and `full_height` because these are the dimensions of region=full, size=full (whether or not it is actually available). However, it may be easier/better to fix that in the description rather than changing the property names.

**Comment by zimeon** [comment]
Agreement at The Hague: clarify language to explain meaning but not change parameter names, can be done in point release.

**Comment by tomcrane** [comment]
(from The Hague)

In a level 0 implementation with `sizes` only, `sizes` means "these are the only requests you can make".

In a dynamic implementation that supports arbitrary sizes, `sizes` means "I'd prefer it if you asked for one of these as I have them cached / they are faster to extract from the JP2, but you can still ask for any size (up to maxWidth/maxHeight)".

If the info.json also has maxWidth (/ maxHeight), should that implied max size always be in the sizes array, if there is one? Not necessarily, the server might be capable of returning 10,000 x 10,000 but still not list that in preferred sizes, which are optimised for the current image and provide hints to clients to help make for a good user experience.

**Comment by jpstroop** [comment]
Eds: add something under the table here: http://iiif.io/api/image/2.1/#technical-properties

 * Server may not support the full width and height
 * This info is still important for making tile requests and knowing the aspect ratio of the image.
