### ISSUE TITLE
prefix/suffix (before/after) makes annotation search term dependent

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#514]
And thus the matched annotations cannot be given their original URIs, if they have any.
The alternative, if we want to maintain the URIs in search is cumbersome as the result list would not be the annotations, but little wrappers around the annotation to capture this search-specific information.

So the choice to be made is between including the URI of the annotation, and including the prefix/suffix text.

**Comment by tomcrane** [comment]
Yes, the "search result with highlighting" annotations might be different, ad hoc, disposable. Are they still annotations?

In manifests for books that have been OCRed, I make contentAsText annos available to give the full text, e.g., http://wellcomelibrary.org/iiif/b18252461/contentAsText/20, one annotation per line. But it's not these that I am searching when you do a "search within", neither in principle or in practice:

http://wellcomelibrary.org/service/iiifsearch?within=http://wellcomelibrary.org/iiif/b18252461/manifest&q=life%20capital

My search results are different annos. These have no relationship with the contentAsText annos asserted in the manifest. However, that's just my implementation. Someone else might could return the matching "by line" contentAsText annotation as a result - in which case it couldn't have the before and after text, as you say (and its rectangle would be the line not the term).

I notice that I don't have @id on either of my types of annotation - which is a bug for the contentAsText annos (and why Mirador won't show them) but maybe as it should be for the ad-hoc, for-highlighting result annos.

Does this mean that this issue is about advice for implementers - if your search results are context-specific to the term searched for, don't give them URIs; if not, do? Context-specific annos could still have an @id (in this case it would include the term, it would be a different anno from the contentAsText anno) but omitting a URI implies that the annos are transient, not intended for later reuse.

**Comment by azaroth42** [comment]
Before/After are for text that's before and after the chars of the annotation, not within the annotation.
Spec needs to be updated to specify this.

Make a new issue for prefix/suffix when you don't know the bounding information for the hit within the text, e.g. line/canvas level transcription, translations, comments etc.

**Comment by azaroth42** [comment]
Closed by resources/hits change to search.
