### ISSUE TITLE
Allow multi-term autocomplete?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#535]
Given that the autocomplete service has all of the parameters of the search service (so it can work from the right set of terms), it could trivially generate a link from the term to the appropriate search to run.  This would be more REST/HATEOAS friendly than making the client construct the url by copying the match content into the q param of the search URL.

e.g. as per first half of:
  http://search.iiif.io/api/search/0.9/#response-1

**Comment by zimeon** [comment]
How does this work in the case of multiple terms in the query? Do we expect that someone typing:

> green bir

be shown matches `bird`, `biro` etc only if they match in the context of the other search term `green`?. Goole works that way and that would then work fine with @azaroth42's suggestion of writing out the full `search` URI (even with possible re-orderings of the terms).

Is this a high bar to require of all auto-complete services? I had imaged, and the 0.9 spec is currently written, as considering autocomplete of a single term. If that is the case then the `search` link doesn't make so much sense because the URI for the single term may not correspond with the complete query.

**Comment by azaroth42** [comment]
I think that would match terms that start "green bir" ... which is likely none.  Not sure how you would tell that you want to autocomplete bir rather than green?

Agreed that the search link would only work for single term queries.

**Comment by tomcrane** [comment]
Do we have to define the behaviour of autocomplete wrt multiple terms or can we leave it up to the server and stay silent?

For example, a simple server autocomplete implementation would just split all the words on space and reduce them to a hashset. It would have no terms with spaces in them, so someone trying to autocomplete  "Vaughan Williams" wouldn't match it - as they typed "v", "a", "u" they would see just "Vaughan" in the term list.

A more sophisticated server may be aware of certain multiple word terms (it may have a list specific to the subject matter) and have a separate entry in its hashset for "vaughan williams", and would match "v", "a", "u" to it. In other words, it matches some multiple word "q" values, but doesn't in general (it doesn't match q params for arbitrary consecutive pairs of words). This behaviour wouldn't feel inconsistent to the end user.

If the autocomplete service is nested in the search service, it can decide how it should construct the autocomplete link to its parent search service to be consistent with how that search service processes a multi word term. 

e.g., in the above case it might construct a term that quoted the special autocomplete term:
"search": "http://example.org/service/identifier/search?q='vaughan williams'&motivation=painting"

..because it knows that the example.org search service will look for the phrase if the query is quoted.

**Comment by azaroth42** [comment]
I think we need to define the behavior if the q param has multiple terms, otherwise different systems will implement mutually incompatible services. Which defeats the point of an interoperability spec.

There seem to be two options:

1.  Treat only the last term as the one to autocomplete, and use the previous terms as context to narrow the set of possibilities.  E.g. green bir would only suggest 'biro' if there is a green biro.
2.  Treat the entire field as a single string to autocomplete on.  Hence if there were no terms with spaces in them, then there would be no autocompleted terms returned.  At which point we might as well define the service to require a single term only.

I prefer option 2, and requiring only a single term.

**Comment by azaroth42** [comment]
How to make progress here? We can remain silent and close wontfix?

**Comment by azaroth42** [comment]
Defer?

**Comment by tomcrane** [comment]
Can we recommend option 2 in the text as the most useful pattern, but still leave it up to implementations? Autocomplete is (I think) for humans only, there might be scenarios where the annotation list and hits returned are more useful to a human (who then follows a RESTfully supplied link to the search service) if they do something other than option 2, although I can't think of one right now.

**Comment by zimeon** [comment]
I think going for option 2 is better than being silent

**Comment by jpstroop** [comment]
:+1: to option 2

**Comment by mikeapp** [comment]
:+1: to option 2

**Comment by azaroth42** [comment]
:+1: to option 2 as well :) Consensus, editor action needed
