### ISSUE TITLE
Clarify Prezi "Image Resources" section (sec6.4 in 2.0, sec5.4 in 2.1) is ONLY for images

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#537]
And that non-image content MUST go in one or more separate AnnotationLists.

iiif-discuss reference: https://groups.google.com/forum/?hl=en#!topic/iiif-discuss/d5GvgpTglUE

**Comment by azaroth42** [comment]
Note in Section 6.3, 4th paragraph:
> Image resources, and only image resources, are included in the images property of the canvas.

**Comment by zimeon** [comment]
After resolving confusion because we've renumbered the old 6.4 to now be 5.4 (http://prezi-21.iiif.io/api/presentation/2.1/#image-resources)...

Seems that there should be forward references to sections [5.4 "Image Resources"](http://prezi-21.iiif.io/api/presentation/2.1/#image-resources) and [5.5 "Other Content Resources"](http://prezi-21.iiif.io/api/presentation/2.1/#other-content-resources) in [section 5.3](http://prezi-21.iiif.io/api/presentation/2.1/#canvas) 4th paragraph where both are mentioned (extending quote from previous comment with suggested additions):

> Image resources, and only image resources, are included in the images property of the canvas. These are linked to the canvas via annotations **as described in [Image Resources](http://prezi-21.iiif.io/api/presentation/2.1/#image-resources)**.  Other content, such as transcriptions, video, audio or commentary, is provided via external annotation lists referenced in the otherContent property **as described in [Other Content Resources](http://prezi-21.iiif.io/api/presentation/2.1/#other-content-resources)**.

Then perhaps clarify restriction to images in the last paragraph of [5.4](http://prezi-21.iiif.io/api/presentation/2.1/#image-resources):

> **Only image resources are included in the images property of the canvas.** Additional features of the Open Annotation data model may also be used, such as selecting a segment of the canvas or content resource, or embedding the comment or transcription within the annotation. These additional features are described in the following sections **([Other Content Resources](http://prezi-21.iiif.io/api/presentation/2.1/#other-content-resources) and [Advanced Association Features](http://prezi-21.iiif.io/api/presentation/2.1/#advanced-association-features))**.

**Comment by zimeon** [comment]
Checking... Forward refs in 5.3 -> 5.4, 5.4. Streamlined version of clarification about restriction to images at end of 5.3. :+1:
