### ISSUE TITLE
Make description of `sizes` compatible with canonical URI syntax

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#544]
The current description of [canonical URI syntax](http://image-21.iiif.io/api/image/2.1/#canonical-uri-syntax) says:

Parameter | Canonical value
--- | ---
size | “full” if the default size is requested, the w, syntax for images that should be scaled maintaining the aspect ratio, and the w,h syntax for explicit sizes that change the aspect ratio.

and the description of `sizes` in [info.json](http://image-21.iiif.io/api/image/2.1/#technical-properties) says:

Technical Property | Required? | Description
--- | --- | ---
sizes | Optional | A set of height and width pairs the client should use in the size parameter to request complete images at different sizes that the server has available. This may be used to let a client know the sizes that are available when the server does not support requests for arbitrary sizes, or simply as a hint that requesting an image of this size may result in a faster response. _A request constructed with the w,h syntax using these sizes must be supported by the server_, even if arbitrary width and height are not.

I see two issues:

  1. Saying that _a request constructed with the w,h syntax using these sizes must be supported by the server_ for the w,h given in `sizes` is at odds with the idea of using `w,` for aspect ratio preserving sizes in the canonical URI syntax
  2. I think we have assumed that `sizes` is for aspect ratio preserving sizes but we don't say that. If that is the intention then it should be explicit, if not then example should probably include a distorting w,h.

My feeling is that for 2) we should allow distorting w,h, but that to address 1) we should say that for aspect ratio preserving sizes, only the width parameter should be given. And thus the requirement for support of requests is that _A request constructed using these sizes, with the w, syntax where width alone is given or w,h syntax where width and height are given, must be supported by the server_

**Comment by zimeon** [comment]
This seems particularly important in the level0 case which is where I was thinking about it in relation to work on generating scaled images to go with static tiles.

**Comment by zimeon** [comment]
I guess this situation also illustrates an issue with the `w,` canonical syntax that I've felt uneasy with for a while. What about images that are narrow and tall? E.g.

 * if I have a 1000,4000 max size image, what is the canonical URI `size` a 250 pixel high version?  I think the answer is `62,250` because the canonical URI `size` `62,` means `62,248` and `63,` means `63,252`.

**Comment by azaroth42** [comment]
+1 to dropping the requirement to support w,h for the sizes.  I can't see a use case for explicitly stating you support a deforming size.

Good question about canonical URI for tall thin images, where one w, could resolve to many ,h images. Seems like ,250 would be a better canonical URL than 62, or 63,  

Do we really need to have both width and height in sizes?  Can we just give the width (or height) for non-deforming images? 

And if we reduce requirements (currently both h and w are mandatory, and the h,w is mandatory too), is that a breaking change?

**Comment by acdha** [comment]
I was working on an implementation earlier today and wanted to support the `!w,h` syntax since we have cached thumbnails which fit within certain sizes. 

I found this issue & am now wondering whether the better way to solve this might simply be to avoid forcing clients to construct a size by simply changing the `sizes` definition to something like “a set of strings containing valid `size` parameters” so it could never drift out of spec with the main URL syntax and clients wouldn't need to implement that portion of the spec to simply to generate a valid request.

**Comment by zimeon** [comment]
Note connection of this issue with definition of `supports` values such as `sizeByWhListed` (see <http://iiif.io/api/image/2.0/#image-information>)

**Comment by jpstroop** [comment]
See also #301

**Comment by azaroth42** [comment]
Reframing the question slightly to try and make progress:

What is the single way in which a client request an image from the sizes array from a level 0 server, and know that it will be successful?  Is it `w,` (per canonical) or `w,h` (per requirement given in sizes)?

Given the spec in 2.0, there is a correct answer to this, and it's `w,h`.  This is from the definition of sizes, in which it states:
> A request constructed with the w,h syntax using these sizes MUST be supported by the server

Thus the canonical syntax is incomplete, and we should fix that bug in 2.1.

We should do our best to not change the definition of canonical for other cases, such that performance will be degraded. For example, if w,h were to become canonical for all sizes, then clients interacting with 2.0 servers but written with 2.1 canonicalization would be slower, and vice versa.  We must also not make backwards-incompatible changes... the spec isn't exactly inconsistent at the moment, it just doesn't work well for level 0 implementations in that they would have to have two copies on disk, one with each syntax.

Given this, I think that the minimal change to answer the "how do I request this image" question, is to have the canonical syntax section explicitly say that `w,h` is the canonical syntax when the region is "full", the size is not "full", and the size is listed in sizes. We then delete the `SHOULD use w, syntax` sentence.  Yes, this amounts to a server-defined canonical syntax :crying_cat_face: but only for a very limited set of requests.

The situation when it would come into play is in tiling requests, where the size of the tile is greater than the dimensions in sizes, and hence there's only one tile for the full image.  This would hit the canonical rule and trigger a `w,h` request, rather than a `w,` request.  But according to the spec, servers MUST support those requests, so this is an optimization issue, not a breaking change.

We should decide on this issue before tackling the sizes in OSD issue (https://github.com/openseadragon/openseadragon/issues/737) to make sure it does the right thing.

**Comment by zimeon** [comment]
I agree with @azaroth42's suggestion above: we should move to `w,h` as the canonical for not `full`. Thus in [section 4.7](http://iiif.io/api/image/2.0/#canonical-uri-syntax) we change canonical for `size` from:

> “full” if the default size is requested,
> the w, syntax for images that should be scaled maintaining the aspect ratio,
> and the w,h syntax for explicit sizes that change the aspect ratio.

to

> “full” if the default size is requested,
> otherwise the w,h syntax.

I note we then will also want to remove the `w,` section in the [Application Notes](http://iiif.io/api/image/2.0/#a-implementation-notes).

**Comment by azaroth42** [comment]
I was trying for something more subtle than that. The reference to `w,` was the sizes sentence:
> The size SHOULD be requested using the canonical syntax of `w,`. 

To make a concrete proposal:

```
"full" if the default size is requested,
the w,h syntax for whole images listed in the [sizes](#technical-properties) list in the information description,
the w, syntax for other images that should be scaled maintaining the aspect ratio,
the w,h syntax for images that should be scaled changing the aspect ratio.
```

**Comment by tomcrane** [comment]
I was just seeing what the wording of canonical size would look like if it incorporated Rob's suggestion of https://github.com/IIIF/iiif.io/issues/544#issuecomment-150639972 and came up with virtually the same text.

**Comment by tomcrane** [comment]
(so +1)

**Comment by mikeapp** [comment]
+1

**Comment by jpstroop** [comment]
+0

**Comment by zimeon** [comment]
+1 for [proposal](https://github.com/IIIF/iiif.io/issues/544#issuecomment-156165684) from me, want to put ditching `w,` on the agenda for 3.0

**Comment by azaroth42** [comment]
+1 to proposal
+1 to adding warning to the spec

**Comment by azaroth42** [comment]
And .... then we all changed our minds

**Comment by azaroth42** [comment]
New proposal:

Add a .warning to 2.1's section 5.2 between the first two tables to acknowledge the inconsistency with the canonical syntax and that clients SHOULD use the canonical syntax for entries in sizes which is `w,` not `w,h`, and the next major version will address the inconsistency.

**Comment by zimeon** [comment]
As I wrote the suggestion 1367a0f I was left with the conclusion that in addition to recommending use of `w,` by clients, one has to also recommend server support for of both `w,` and `w,h` for aspect ratio preserving images. Ugly as this is, as a level0 implementer I will change my code to support both forms and be happy knowing that OSD will still work (`w,`) and someone following the description of `sizes` (`w,h`) will still be OK. 

Looking forward to 3.0 when we can make `w,h` canonical...
