### ISSUE TITLE
Clarify canonical syntax for square

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#560]
pixel region or just "square"?

"square" is not as precise as "full", so even though both are shorthand for something that could be expressed as pixels, the fact that it's up to the server to decide what square you'll get makes me feel like it should be the pixel region--this also means that if you don't like the square you got, you _could_ adjust it without getting the info.json.

**Comment by azaroth42** [comment]
:+1: to pixels for canonical version of square

**Comment by azaroth42** [comment]
Errr, what if the image is square?  Is the canonical form "full" ?

**Comment by jpstroop** [comment]
Seems logical. Annoying, but logical.

**Comment by jronallo** [comment]
Where can I see more about how squares would work? Is this only for a centered square image? 

One of the things I did in the djatoka gem was to allow the square to be in the center of the image whether landscape or portrait (but using the full width of the short length), or to start at the top left or bottom right of the image. We then store some metadata (top left or bottom right) about any image where the square should not be centered because it would crop out a significant portion of an image or lop off someone's head. This has been sufficient for creating thumbnails and search results pages for our images.

https://github.com/jronallo/djatoka/blob/e8d4f77311c47563da35f46a79c2508cc215593f/lib/djatoka/common.rb#L121

**Comment by jpstroop** [comment]
Check out the [2.1 Draft, section 4.1](http://iiif.io/api/image/2.1/#region)

**Comment by zimeon** [comment]
I suppose I agree with the canonical form of `square` being pixels, or `full` if the image happens to be square. (I say "suppose" because it is odd to have `square` and `full` treated differently, would be more consistent to have neither or both be canonical...)

**Comment by mikeapp** [comment]
+1 to `full` as canonical if the image is square

**Comment by no-reply** [comment]
:+1: to pixel expression.

With respect to `full` for square images. Is the canonical representation of `0,0,[image_w],[image_h]` also `full`?

**Comment by azaroth42** [comment]
Add parenthetical statement on first line of region in 4.7 table to note that the full image is being requested by a square image with region square.

**Comment by zimeon** [comment]
agree
