### ISSUE TITLE
Clarify non text/plain formats okay for annotations

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#610]
The only format mentioned in the spec is text/plain. It should be clearer that this is not a requirement, and text/html text/markdown or any other is possible. A recommendation for text/plain or text/html might be useful, however?

From: https://github.com/IIIF/mirador/issues/585

**Comment by zimeon** [comment]
While the section on [Embedded Content](http://iiif.io/api/presentation/2.0/#embedded-content) with `cnt:ContentAsText` shows `text/plain`, I note that the section on [Comment Annotations](http://iiif.io/api/presentation/2.0/#comment-annotations) shows `text/html` in the example. I'm inclined to agree that the embedded content section. I agree that pointing out that `text/plain` and `text/html` are the recommended media types would make sense, should one then make specification of the media type a _SHOULD_ rather than a _MAY_?

**Comment by tomcrane** [comment]
Need to make sure that people don't interpret "cnt:contentAsText" as "if you're embedding the annotation content you must use plain text".

Maybe an additional sentence after http://iiif.io/api/presentation/2.1/#embedded-content:

> When embedding a resource of type cnt:contentAsText, the format SHOULD be provided, and It is RECOMMENDED that the format be either "text/plain" or "text/html"

**Comment by zimeon** [comment]
+1 to @tomcrane's suggested text, should replace the current:

> The media type _MAY_ be given using a format field.

an perhaps be switched to before the language sentence?

**Comment by azaroth42** [comment]
See: http://prezi_issues.iiif.io/api/presentation/2.1/#embedded-content

**Comment by jpstroop** [comment]
:+1:
