### ISSUE TITLE
Limiting max height and width that can be requested

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#620]
See the [thread started by Glen yesterday](https://groups.google.com/forum/#!topic/iiif-discuss/j-tg5F7J6VM). We've heard it before, and I was about to add my own slightly different use case, but @tomcrane has already done so. I'm perfectly happy to give you `full` of anything, but from a practical, systems perspective, I can't do it because the full image is just too large (i.e. scrolls, and some other huge prints we have) and the server will time out.

Yes, practically speaking, if you can get the tiles you can recreate the whole image. However, we've heard enough times now that it would make people comfortable and further adoption if we could find a solution.

The cheap solution would be to add a predicate like `fullAvailable: true|false`, and force clients to work with `sizes` to determine what they can get. The better solution, in my opinion, is something like the discussion around #277.

**Comment by azaroth42** [comment]
I believe that this issue is dependent on some solution to #621.
Do we want to tackle them for 2.1 or defer to a subsequent version?

**Comment by jpstroop** [comment]
-1 to my initial `fullAvailable: true|false`suggestion. Agree that we should find a way to solve this with `supports` and compliance levels.

**Comment by tomcrane** [comment]
Another way of framing it - "you can construct any request you like given the ```supports``` above, as long as that request isn't asking for an image greater than n square"

**Comment by tomcrane** [comment]
Scenarios:

full/full is prevented by policy but the image service otherwise supports arbitrary - so the user constructs a request that crops by 1px and walks away with what is essentially the full image. :-1: 

Astronomical / map images: image server is perfectly capable of ```/full/!5000,/```, or any arbitrary region in theory, but in practice has to impose a limit on the response image dimensions to prevent overload. We don't want to prevent any fully-compliant, supports-everything request UNLESS it would result in an image that exceeds our danger threshold. Selecting your perfect arbitrary crop that isn't in ```tiles``` or ```sizes```, and embedding that image in your blog post, is supported and encouraged. You're unlikely to exceed sizes set for protection of servers in this scenario. 

Some publishers set n=512 because of policy, some publishers set n=15000 to prevent server meltdown - the spec covers both without having to state the reason for the limit

**Comment by zimeon** [comment]
My tendency is toward a solution that allows servers to express their limit which would support the n=15000 scenario, and allow validation/testing up to the specified limit. However, the n=512 scenario would probably be supported by a flag that indicated `biggerThanTilesizeSupported` as true/false (obviously _not_ suggesting that name)

**Comment by jpstroop** [comment]
I think you still need to know the full width and height, e.g. so that you can do the math to get the non-square tiles at the right and bottom edges in the OSD case. So I'm not sure why you'd need `biggerThanTilesSupported`.

largestSupported=n seems like it would be sufficient. And we change spec of what full means to be w/h unless largestSupported is supplied.

**Comment by tomcrane** [comment]
What if the policy requirement doesn't coincide with tile sizes - e.g., tiles are 512 but legal department says 1000 px is the biggest image they can permit a *single* URI for?

What would it mean to have a new largestSupported property?

For servers, it's not a big deal - e.g., IIPImage has MAX_CVT and the usage is obvious. When constructing the info.json a server can show largestSupported if any of...

* width or height greater than the absolute server limit (assert this limit)
* width or height greater than the policy limit for this particular image, if any (assert this limit if present and smaller then absolute limit)
* server supports ```sizeAboveFull``` (show smaller of two limits)

For publishers - don't set your largestSupported policy to be smaller than than your tile size! - could be a danger for 1024 tiling servers

For clients, I can think of one use case in the Universal Viewer; we have "download current view" which constructs an Image API request coincident with the viewport; it would potentially have to scale this down to produce a valid request but that's easy to do.

Auth: for some publishers there could be a degraded info.json which is identical to the non-degraded except in one detail - the value of largestSupported (512 degraded, server maximum otherwise). Although in this scenario it would be difficult for the end user to work out what was different if they are just deep-zooming around.

**Comment by zimeon** [comment]
@jpstroop - certainly not in any way suggesting that `width` and `height` aren't necessary, they are the foundation of all math for tiles etc..

@jpstroop, @tomcrane - I agree that a specific limit, say `largestSupported`, would be more useful than `biggerThanTilesSupported`, [was](#issuecomment-161951849) just pointing out that even a `biggerThanTilesSupported` flag met one of the use cases. I do like the use case for a specific limit allowing a viewer to control a download current view feature -- that seems quite compelling

**Comment by mikeapp** [comment]
What about additionally supporting a maximum pixel count (max w*h) option as a less restrictive alternative to `largestSupported`?

I'd like to provide the most flexibility possible for annotation use cases. For instance, a `largestSupported` of 1024 would break full-size display of the annotation area for an annotation such as this: http://scale.ydc2.yale.edu/iiif/4aaa9871-503f-4eac-a1d5-aa635969c659/766,838,500,1548/full/0/native.jpg

**Comment by jpstroop** [comment]
I don't see a problem with @mikeapp's suggestion. `largestAreaSupported`?

**Comment by azaroth42** [comment]
I understand the rationale behind `largestAreaSupported` but I don't think that any use cases support it? The server should provide as much access as possible, and no one has said that they want to restrict access by total pixel count, rather than edge length.

And (at 5:30 this morning :S) I had the realization that what we're talking about I think should be a property of the profile, not of the image.  The /image/ doesn't have a max height and width, the service that provides access to the image has those restrictions in the same way that it can deliver a set of formats, qualities and so forth.

So my proposal:
  * Add `maxHeight` and `maxWidth` as OPTIONAL properties in Section 5.3.
  * Maybe add `maxArea` as OPTIONAL in Section 5.3, if there are systems willing to implement

```
{
  "profile" : [
    "http://iiif.io/api/image/2/level2.json",
    {
      "formats" : [ "gif", "pdf" ],
      "qualities" : [ "color", "gray" ],
      "maxHeight": 2048,
      "maxWidth": 2048
    }
  ]
}
```

**Comment by jpstroop** [comment]
I'm fine with this, and good catch that it belongs in the profile. I think we can get away with one predicate, `maxSize` or `maxDimenson`. I don't think we have a use case for limiting one dimension but not the other, do we?

**Comment by jpstroop** [comment]
I think asking for something that is bigger than supported is a 404 (Not Found):

 * In the level 0 / static impl. case it's actually true, the image isn't there
 * For any case it's not a 400 if you've built a well-formed request URI according to our syntax (at least to me)
 * In 7.2 for 404 we say "...[if] the value of one or more of the parameters is not supported for this image", which feels like the case here.

That said, we often recommend that bad or unsupported parameters for well-formed requests should be a 400:

 * If the requested region’s height or width is zero, or if the region is entirely outside the bounds of the reported dimensions, then the server should return a 400 status code.
 * If the resulting height or width is zero, then the server should return a 400 (bad request) status code.
 * A rotation value that is out of range or unsupported should result in a 400 status code.
 * A quality value that is unsupported should result in a 400 status code.
 * A format value that is unsupported should result in a 400 status code.

**Comment by zimeon** [comment]
I agree that 404 "Not Found" is the best response code for "too big" according to the limits specified. I think that in practice most clients will not really distinguish between different 4xx codes except where auth is concerned.

(I note the in conversation at the meeting yesterday, [406](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.7) was mentioned but I think this is not a good choice.)

**Comment by jpstroop** [comment]
re 406:
> ...not acceptable according to the accept headers sent in the request

Yes, no.

**Comment by tomcrane** [comment]
I agree that we don't need separate maxWidth and maxHeight, but maxArea seems a real use case as per http://wellcomelibrary.org/iiif/collection/b19974760 and could be optional.

**Comment by zimeon** [comment]
If we have `maxWidth` and `maxHeight` and `maxArea` the test is:

```
if (maxWidth and not maxHeight):
    maxHeight = maxWidth
if ((maxWidth and (width>maxWidth or height>maxHeight)) or
    (maxArea and (width*height > maxArea)):
   raise TooBig()
# else server image
```

so my sense is that it does not cost much to implement both. Main cost is specification complexity.

**Comment by azaroth42** [comment]
Remaining eds at Ghent agree for the second time that maxArea is valuable and the above algorithm is sufficient.  And just leave it to people reading the errors section to pick an error code.

**Comment by jpstroop** [comment]
To be clear, proposal is all three?

**Comment by jpstroop** [comment]
If so, could we at least get it to two: maxArea and maxDimension?

**Comment by zimeon** [comment]
We are talking about three. Use case for both `maxWidth` and `maxHeight` is a server that wants to provide non-distorted scaled versions to some size (don't recall who said that one). IMO, it is cleaner to have both `maxWidth` and `maxHeight` as that matches our optional support for non-square tiles too.

**Comment by jpstroop** [comment]
So is a server allowed to indicate all three? That could get confusing, and it feels like we're offering two mechanisms to do nearly (admittedly not exactly) the same thing. Seems a little burdensome to clients as well.

**Comment by zimeon** [comment]
Again yes. My [psuedo-python above](https://github.com/IIIF/iiif.io/issues/620#issuecomment-163959868) convinced me that it is trivial from a server point-of-view.

**Comment by jpstroop** [comment]
So presumably area must be less than w*h?

**Comment by zimeon** [comment]
If `maxArea > maxWidth*maxHeight` then the area condition will never be hit. Useless, but no harm done.

**Comment by zimeon** [comment]
If `maxArea > maxWidth*maxHeight` then the area condition will never be hit. Useless, but no harm done.

**Comment by zimeon** [comment]
It seems most likely that servers will implement either `maxWidth` (and possibly `maxHeight` if non-square restriction) _OR_ `maxArea`. However, it seems easiest to specify how to implement both that to specify rules for specifying one or the other.

**Comment by jpstroop** [comment]
I guess I'm +0 if other eds are :OK:, but this feels sloppy to me.

**Comment by tomcrane** [comment]
3 use cases:

1. Technical constraints
2. Licensing
3. Practical annotation rectangles

1 and 2 only really require a single dimension to keep servers and image sales happy.
3 wants the most pixels that won't upset 1 and 2 but would prefer to use its allowance of pixels more flexibly.

If 3 is dropped it becomes very simple and clear. I don't think I mind all three, although I see why you are +0 on it. 

So I'm +1 on all three if 3 is an important use case.

**Comment by jpstroop** [comment]
I think my feeling is that we can accomplish all three with area, and if area is too tough to explain to a lawyer, then adding a single max dimension (which doesn't keep you from requesting non-square tiles) should suffice.

**Comment by azaroth42** [comment]
I'm +1 on maxHeight+maxWidth, and -0 on maxDimension:
  * We already have the width and optional height pattern established in both canonical syntax and the tiles description.
  * There's no cost to using maxWidth plus optional maxHeight, whereas we're painting ourselves in a corner if we use maxDimension.  If maxHeight is never used, there's no real cost.
  * An implementation might want to have a max dimension of 1/16th of the full size, regardless of the dimensions of the image.  So a 16000 x 8000 image would be 1000 x 500 for the maximum height and width

I'm -0 on maxArea:
  * I understand the desire, I think the practical implementation is easy (per Simeon's code) ... but no one wanting to restrict access has wanted it so I think it fails the use case test.
  * If used without maxWidth/maxHeight on large images, it's not valuable.  If you're okay with 512x512, and maybe okay with 1024 x 256 ... are you really okay with 26216 x 10?
  * It adds complexity ... and given the above, I believe unnecessarily.

P.S. Why do we _require_ both width and height for sizes rather than just width? So a server can express arbitrary deforming sizes? Use case??  I know we can't change it now, but in 3.0 couldn't we either make height optional, or drop it completely? (New issue?)

**Comment by tomcrane** [comment]
Given the discussion on what this issue means a server should do in response to a size parameter that it can't support, is there an argument for an additional size parameter "best" (or similar)?

/full/best/0/default.jpg

/100,100,10000,10000/best/0/default.jpg

This would have definite utility - the UV offers a "download high res" option that currently requires out of band knowledge of the server's abilities - all a viewer need do is ask for /full/best/...

**Comment by tomcrane** [comment]
(or "max")

**Comment by tomcrane** [comment]
@glenrobson - any comments?

**Comment by jpstroop** [comment]
> If used without maxWidth/maxHeight on large images, it's not valuable. If you're okay with 512x512, and maybe okay with 1024 x 256 ... are you really okay with 26216 x 10?

[This was @mikeapp's idea](https://github.com/IIIF/iiif.io/issues/620#issuecomment-162302862), not sure if it's a use case he actually has, but I agree it's compelling, esp in @glenrobson's case where it sounds like the max width and height are going to be quite small.

**Comment by jpstroop** [comment]
I would be OK with 26216 x 10 but if others weren't, setting a maximum length (which I believe we're saying maxWidth without maxHeight effectively does?), then I guess I can :+1: allowing all three.

**Comment by azaroth42** [comment]
It doesn't help were max width and height are small. 
See algorithm here: https://github.com/IIIF/iiif.io/issues/620#issuecomment-163959868

If any of the checks are true, then the error condition is triggered.  As we don't understand it, then I think I'm going to downgrade my -0 to a full -1.

And given that the main driver is to limit max width and height to something small (give or take), maxArea really just _never_ helps?

**Comment by azaroth42** [comment]
> (or "max")

Or ... "default" :wink:

**Comment by jpstroop** [comment]
> It doesn't help were max width and height are small. 
See algorithm here: #620 (comment)

To clarify, if it were me I'd rather set max area to 262144 and not set a max dimension at all. That way a user could get 512×512 or 256×1024, etc. If that's not tight enough for @glenrobson, maybe he can set a max dimension as well, but I'd really prefer area for my scroll use case where the only constraint is technical.

**Comment by mikeapp** [comment]
I agree with @jpstroop on the large image case.  For larger images one could use max area and perhaps height/width in addition if there are specific performance or policy concerns.  For instance, my Djatoka-based server can return a 0,0,26000,10/full image quickly, but would fail with a taller image (e.g., 0,0,26000,5000).   (The same success and failure conditions would apply to a tall narrow image.)  I can't simply permit 26000 square tiles, and limiting either the height or the width would impose an artificial constraint: do I limit to 26000x1000, 1000x26000, or something in between?

**Comment by jpstroop** [comment]
Yup, exactly. I can send you the top 20 pixels of the entire length of one
of our scrolls....

**Comment by glenrobson** [comment]
When it went through our senior management team discussions they did settle on 512px on the long edge as the restriction but its relatively arbitrary (and I only suggested it as I thought this was what others were doing).  If only max area was supported I could probably get this approved as it still requires stitching to generate the full image and if it would help with some of the annotation use cases I would be willing to try. 

Regarding @tomcrane comment on /full/best/0/default.jpg I would like to be able to support a URL that will blindly get the best image I can provide without working it out from the info.json. I thought it may be required for the EDM Web Resource id but in the end we used the thumbnail URL. It still may come up that someone would want to use this URL.

Regarding the UV download functionality this is something we are looking at. We have two use cases, the first is where we would sell the high quality image and I think we'd do this by putting a link in the Metadata to say 'purchase' which would link to our eCommerce system. For public domain images I would probably look at disabling the maxwidth/area restriction for these. I'm not sure how the discussions will go but it could be that we don't give the full resolution for these images and so a /full/best/0/default.jpg would be useful.

**Comment by mattmcgrattan** [comment]
+1 for a 'best' option.

**Comment by mikeapp** [comment]
`best` or `max` could return a size anywhere from `/full/` down to the tile size on the long edge, its going to be difficult to use in a consistent way.  Would it be OK if the user clicked 'download high res' and got a 350x512 image?  I think you'd need to check the `info.json` and not offer the option if the server doesn't support a reasonably high resolution download.

Also, if someone codes a client to display images using `/best/` in order to work around tile size limitations, it could have unfortunate consequences when hitting a server that can return a full-scale image.   Given the proposed size restrictions I'd really like the option to indicate that I'll accept a smaller size, e.g.,  `/0,0,2000,2000/<1000,/` for 'up to 1000 wide' when creating links without loading `info.json`.  But that would add even more complexity on the server side :frowning:

**Comment by zimeon** [comment]
This one seems to be going round again. Having read the comments I am still in favor of `maxWidth` and `maxHeight` and `maxArea` because:

  1. Current use cases and server implementations implement `maxWidth` so this seems like the most clearcut (e.g. `MAX_CVT` in (IIPServer](http://iipimage.sourceforge.net/documentation/server/) )
  2. I would add `maxHeight` for consistency with our other separations of width and height in tiles etc., even though use of these today is low/none
  3. The transcription use case requires `maxArea` to allow tiles and long-thin images. (We should perhaps note that servers can't use `maxWidth/maxHeight` if they intend to allow long-thin images.)

If we are happy with 2 and 3, then I think 1 still gets us the 80% case.

I'm really not sure about the `/best/` or `/max/` or `/<1000/` proposals for size. I think we'd be better separating that off into a different thread.

**Comment by mikeapp** [comment]
Agree on moving discussion of 'best' to a new issue.

**Comment by jpstroop** [comment]
I think adding `maxWidth`, optionally `maxHeight` (to match our approach to tiles) and also `maxArea` seems like the right compromise.

:+1: to moving the discussion of `/best/` etc. elsewhere. I'm generally skeptical of introducing more special keywords.

**Comment by azaroth42** [comment]
:+1: to maxWidth, maxHeight, maxArea (all optional, though just maxHeight would be invalid)
And :+1: to separating /max/ to another issue

**Comment by jpstroop** [comment]
and it goes without saying that `maxWidth` must be =< to `maxArea`.

**Comment by jpstroop** [comment]
wait...maybe that's not true?

**Comment by zimeon** [comment]
@jpstroop - I think servers will usually specify either `maxWidth & maxHeight` _OR_ `maxArea`, but not both. Perhaps there are some edge cases where both might be useful and I think that will only be in the regime when `maxWidth * maxHeight >> maxArea`, so that `maxArea` defines the largest tile size and `maxWidth & maxHeight` define the maximums for the large dimensions of long-thin or tall-thin rectangles.

**Comment by mattmcgrattan** [comment]
re: /best/ or /max/ that's a nice to have, but for us it doesn't solve any pressing use cases that we couldn't easily solve another way.

Size restrictions for us come up almost entirely in terms of concerns about potential commercial exploitability, and where those use cases would be solved by the combination of maxArea and maxWidth/Height.

**Comment by azaroth42** [comment]
I think we're at consensus about this issue? needs_pr ?

**Comment by zimeon** [comment]
Agreed, I'll try to come up with a PR sometime soon
