### ISSUE TITLE
Cannot generate valid info.json if full/full is not supported

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#621]
__Issue:__
As per #620, some images cannot be delivered at full/full for policy and/or technical reasons.  The lowest level of requirements for compliance with the Image API (level 0) requires support for full size and full region.  The first profile in the info.json profile list MUST be a compliance URI. Thus the images where full/full cannot be delivered cannot be described using info.json

__Proposal:__
The minimal fix to this (IMO) bug is to introduce a null compliance URI (level null? level -1? level custom?) that has no requirements at all. Then the actual capabilities for the image would need to be described in a separate profile object.

**Comment by jpstroop** [comment]
Having to declare level null (or whatever) and then enumerate every feature the server supports (in the case of Loris that's _every_ feature), and having to do it only when images are, at least in my use case, above a certain size threshold, seems very heavy-handed.

**Comment by azaroth42** [comment]
Do you have a different backwards compatible suggestion that we could implement in 2.x ?

**Comment by jpstroop** [comment]
Is to make a feature _not_ required at a certain level a breaking change? I don't think so, so why don't we just make `full` optional at all levels?

**Comment by jpstroop** [comment]
Hmmm... But having to add `fullSize` to the `supports` array in your info.json might be a breaking change.

**Comment by zimeon** [comment]
I just spent a few minutes rereading the [Compliance document](http://iiif.io/api/image/2.0/compliance.html) and I notice a few things:

  * It is not explicit that all combinations of all supported parameters must be supported in order to meet compliance. Thus while region=`full` and size=`full` must be supported at all levels, it doesn't actually say that `/full/full/` need be. That said, I think we have usually assumed the implication
  * The note about level0 support at the bottom talks only about tiles that must be supported, it does not mention `/full/full/` or optional support for specified `sizes`. I will admin that I did not think about support for `/full/full/` in my static tiles implementation and, of course, OSD does not use it.

I think the bottom line is that it doesn't make sense for `/full/full/` to be a requirement for compliance because then no large image will be compliant... how we get there is the issue

**Comment by jpstroop** [comment]
> I think the bottom line is that it doesn't make sense for /full/full/ to be a requirement for compliance because then no large image will be compliant... how we get there is the issue.

I'm trying to get my head around whether or not this is a breaking change. I think it _is_ for clients, who right now have no need to check whether `/full/full/...` is possible, and it _is not_ for servers, since we'd be adding the ability to restrict the size, but not taking anything away. (Unless we changed the structure or requirements of `info.json`, of course, and I don't think we're in danger of doing that here).

I'll say it. This and the broken c14n issue are beginning to give me an appetite for a major release. The reality is that these breaking changes are small, and exist to solve edge cases that don't actually apply to very many people. Yes, it would be 3.0 for the sake of semver semantics, but, practically speaking, it would be nowhere near as painful as the 1.1 -> 2.0 jump.

Happy to be argued against, and if we want to do a breaking release we probably need delay and do a more comprehensive review of the issues (given the opportunity) but I think it's work putting on the table.

**Comment by azaroth42** [comment]
I agree with @zimeon that the current text doesn't say that all combinations must be supported.  
So long as you can get some region at full size, and the full region at some size, you're compliant.  Thus in #620 we're adding a backwards compatible extension to allow the server to describe its limits that it already (clearly) has, rather than breaking existing functionality.

If we agree, the change is editorial to clarify the meaning of the combinations in the compliance level document which is currently ambiguous.

**Comment by jpstroop** [comment]
Reading Simeon's post more closely, I agree. Feels like a little bit of a loophole, but we're not in the wrong to clarify it, and that seems like the correct way forward.

**Comment by jpstroop** [comment]
> If we agree, the change is editorial to clarify the meaning of the combinations in the compliance level document which is currently ambiguous.

:+1: from me.

**Comment by azaroth42** [comment]
@zimeon I assume you'll take care of this with the PR for #620?
