### ISSUE TITLE
iiif:supports values in example are relative URLs

### ISSUE THREAD

**Issue by VladimirAlexiev** [IIIF/iiif.io#626]
I saved the example at the end of section http://iiif.io/api/image/2.0/#image-information as [image-iiif-example.jsonld](https://gist.github.com/VladimirAlexiev/7c917c189c35aaee563e). The problem is that these values are relative URLs
```json
      "supports" : [
          "canonicalLinkHeader", "rotationArbitrary", "profileLinkHeader"
      ]
```

* Run it through http://json-ld.org/playground/ and in tab Expanded I see `"http://json-ld.org/playground/canonicalLinkHeader"`
* Run it through `riot --formatted=turtle` and I see 
```turtle
iiif:supports  <file:some-local-path/canonicalLinkHeader>
```

**Comment by azaroth42** [comment]
That used to work in the playground (admittedly before the most recent playground renovations, so it could have been a bug).  Note that the features are explicitly defined in the context:

For example, canonicalLinkHeader is iiif:canonicalLinkHeaderFeature:
    https://github.com/IIIF/iiif.io/blob/master/source/api/image/2/context.json#L31

(does some reading...)

http://www.w3.org/TR/json-ld/#type-coercion

So the bug is that the context should use @vocab not @id to force the term expansion.

**Comment by VladimirAlexiev** [comment]
So the best way for me to learn JSONLD is: post bugs to @azaroth42  :-)

**Comment by azaroth42** [comment]
JSON-LD Playground demonstrating the fix: http://tinyurl.com/hv33a7u
Fix Branch link: http://friday_issues.iiif.io/api/image/2/context.json

**Comment by azaroth42** [comment]
Okay, site is back in the right state for review. +1s?

**Comment by jpstroop** [comment]
Played around w/ it. Makes sense. :+1:

**Comment by mikeapp** [comment]
:+1:

**Comment by azaroth42** [comment]
Now properly closed :)
