### ISSUE TITLE
Create Newspaper IG landing page

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#647]
iiif.io/community/newspapers.md

Link to the folder of notes
Include the purpose bullet points

**Comment by zimeon** [comment]
URI will be <http://iiif.io/community/newspapers.html> I assume (not .md). Would be nice to go ahead with this promptly

**Comment by azaroth42** [comment]
Sorry, yes, it would be .md in the repo and .html in the web.

**Comment by zimeon** [comment]
Just save us having to refer to the google doc, draft if newspaper IG plans was:

## Purpose of Newspaper special Interest group

  * To determine development and usage of IIIF for digital newspapers
  * To demonstrate best practice in exploitation of IIIF for newspapers
  * To promote usage of IIIF for newspapers
  * To consider related formats, especially serials 
  * To explore and exploit possibilities for search, discovery, and annotation of newspapers

### Organization

  * monthly virtual meeting
  * Google doc to share plans for now, in IIIF folder
  * presence on IIIF.IO website
  * communicate via IIIF-Discuss
  * piggyback on IIIF face to face meetings (twice/year)
  * Karen Estlund and Alastair Dunning to coordinate

**Comment by zimeon** [comment]
Since we have a number of WGs now, probably useful to have a WGs page to itself which can list/link all active/inactive WGs and explain more as necessary. Proposal (with input from @azaroth42):

  * <http://iiif.io/community/> -- current content plus link to /community/wg 
/community
  * <http://iiif.io/community/wg/> -- list of all active (and layer also inactive) WGs
  * <http://iiif.io/community/wg/newspapers.html> etc. -- page for each WG

**Comment by azaroth42** [comment]
Slight revision to use "group" as a more intuitive and less specific as to "working" vs "interest".

I think the current list is: 
 * manuscripts
 * newspapers
 * museums
 * av

**Comment by zimeon** [comment]
:+1: on amendment wg -> group

**Comment by jpstroop** [comment]
:+1:

**Comment by mikeapp** [comment]
:+1: agree on wg -> group

**Comment by tomcrane** [comment]
:+1:
