### ISSUE TITLE
When we have maxWidth/maxHeight/maxArea, should there be a way to ask for the largest size for a given region?

### ISSUE THREAD

**Issue by zimeon** [IIIF/iiif.io#663]
Separating this from #620, comments so far:

@tomcrane wrote: Given the discussion on what this issue means a server should do in response to a size parameter that it can't support, is there an argument for an additional size parameter "best" (or similar)? `/full/best/0/default.jpg` or `/100,100,10000,10000/best/0/default.jpg`.  This would have definite utility - the UV offers a "download high res" option that currently requires out of band knowledge of the server's abilities - all a viewer need do is ask for `/full/best/`... (or "max")

@azaroth42 wrote: Or ... "default" :wink:

@glenrobson wrote: Regarding @tomcrane comment on `/full/best/0/default.jpg` I would like to be able to support a URL that will blindly get the best image I can provide without working it out from the info.json. I thought it may be required for the EDM Web Resource id but in the end we used the thumbnail URL. It still may come up that someone would want to use this URL. ... For public domain images I would probably look at disabling the maxwidth/area restriction for these. I'm not sure how the discussions will go but it could be that we don't give the full resolution for these images and so a `/full/best/0/default.jpg` would be useful.

@mattmcgrattan wrote: +1 for a 'best' option.

@mikeapp wrote: best or max could return a size anywhere from `/full/` down to the tile size on the long edge, its going to be difficult to use in a consistent way. Would it be OK if the user clicked 'download high res' and got a 350x512 image? I think you'd need to check the info.json and not offer the option if the server doesn't support a reasonably high resolution download. Also, if someone codes a client to display images using /best/ in order to work around tile size limitations, it could have unfortunate consequences when hitting a server that can return a full-scale image. Given the proposed size restrictions I'd really like the option to indicate that I'll accept a smaller size, e.g., `/0,0,2000,2000/<1000,/` for 'up to 1000 wide' when creating links without loading info.json. But that would add even more complexity on the server side :frowning:

**Comment by azaroth42** [comment]
I think the use case is clear, and the implementation is easy and obvious. So :+1:
I would prefer `max` to `best`, as best is a qualitative statement rather than technically descriptive. Maybe the maximum size is not the "best" size.

For 2.x it would need to be optional at all levels for compliance to avoid a breaking change. And then I would say level 1 in 3.0 as it's trivial to do, even at level 0.  I would entertain level 0 if someone wanted to argue for it.

**Comment by tomcrane** [comment]
:+1: "max" works for me.

**Comment by jpstroop** [comment]
`max` is consistent with `maxArea`, `maxWidth`, `maxHeight`, so :+1: to that as the term.

It seems to me that in 3.0 we could drop `full` as an option for the size parameter altogether. Is there a use case for asking for something bigger than the server is willing to give you? To me, `max` just serves to tighten the semantics following our clarification that `full/full` never has to be supported.

I'm not a fan of all of these special keywords, so anything we can do to remove one….

**Comment by azaroth42** [comment]
@zimeon, @mikeapp Okay with 'max' option for size?

**Comment by azaroth42** [comment]
Given #683, I think what we mean by `max` is:

> The extracted region is scaled to the largest, aspect-preserving size that the server can deliver, up to the equivalent of `full` but not beyond.  If the server cannot deliver sizes up to `full`, then it SHOULD record the sizes it will deliver in a [profile][#profile-description].

**Comment by mikeapp** [comment]
:+1:  I'm OK with `max` size

**Comment by zimeon** [comment]
I do not like special keywords so I want to go back and question the use cases before we agree on a `max`:

  1. @tomcrane's use case of UV wanting a high-res download seems already supported with `w,h` calculated based on `maxWidth/maxHeight/maxArea`. UV will have already downloaded `info.json`so no extra burden there
  2. @glenrobson's comment is I think about programmer convenience
  3. @mattmcgrattan's comment +1 for a special keyword but does not describe a new use
  4. @mikeapp's comment points out some potential problems with a special keyword. The use case he describes would not be supported by `max`

So, it seems that with current input on use cases we are balancing client developer convenience against API complexity -- and this would only really be convenient if it were mandatory, which it can't be (until 3.0 and even then we'd be unlikely to make it level 0). I'm not sure that is a good compromise. I think I'd prefer to explain the math to calculate `w,h` which would be something along the lines of:

```
# given rw, rh from the region, we want sw, sh which is the max size supported <= rw, rh
sw=rw
sh=rh
if (maxWidth and not maxHeight):
  maxHeight = maxWidth
if (maxWidth and rw>maxWidth):
  scale = maxWidth/rw
  sw = maxWidth
  sh = int( rh * scale )
if (maxHeight and sh>maxHeight):
  scale = maxHeight/rh
  sw = int( rw * scale )
  sh = maxHeight
if (maxArea and sw*sh > maxArea):
  scale = sqrt( maxArea / (rw*rh) )
  sw = int( rw * scale )
  sh = int( rh * scale )
```
modulo a little thought to make sure this handles odd cases gracefully. I'll admit this isn't trivial but adding a `max` size with explanation, levels and feature name isn't either.

**Comment by tomcrane** [comment]
I agree that with ```maxWidth/maxHeight/maxArea``` in the spec, ```/[region|full]/max/0/default.jpg``` is convenience for the UV's "download hi-res image" use case, and once baked into manifesto or similar, can be forgotten about for clients built on those libraries.

However, I think the ability to walk up to an Image API endpoint and ask for ```/full/max/0/default.jpg``` might be more than developer convenience. Maybe ```/full/max/``` is the new ```/full/full/``` - the thing you do when showing somebody the API, the thing people bake into very simple scripts for grabbing images.

It might actually encourage publishers nervous about their server performance, or publishers with lots of huge images never intended for full download. You can safely set a lower maximum size than maybe you would currently (off-spec), because you no longer mind having to return something other than a 200 for a /full/full/ request. As it sinks in, people just stop making /full/full/ requests when kicking the tires because they are aware that it's an "uncontrolled" request that might break. The earlier that shift in perception happens the better.

I've got IIPImage's MAX_CVT set to a figure that covers all but a handful of the Wellcome Library's images, but I'd consider dialing that down to 5000 if ```/full/max/``` was commonly understood by humans as well as software. It encourages reuse *and* protects my servers at the same time. Even something like 2000 would be reasonable for some institutions; high enough for a good view, low enough to avoid melting servers or allowing people to walk away with print-ready images.

I think what I'm trying to say is that /full/max/ actually helps sell the standard (to those last few holdouts...)

**Comment by jpstroop** [comment]
I'm anti-keyword as well (as I said above: https://github.com/IIIF/iiif.io/issues/663#issuecomment-166312822). The prospect of being able to kill "full" as a size in 3.0 (see #678) helps me feel better about it.

**Comment by azaroth42** [comment]
:+1: to `max` keyword in 2.1

**Comment by zimeon** [comment]
:+1: introducing `max` now, deprecating `full` for removal in 3.x.

**Comment by mikeapp** [comment]
:+1: to deprecating `full`

**Comment by tomcrane** [comment]
:+1: ```/full/max/``` is the new ```/full/full/```

**Comment by jpstroop** [comment]
All hail max!
