### ISSUE TITLE
Allow alternate endpoints

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#684]
As per discussion at Ghent, introduced by Petr Pridal, there is a limited number of connections that a client will use at a point in time that connect to a single hostname.  This is an issue when multiple tiles of a single image, or many thumbnails from multiple images are needed at the same time to populate a UI.

The typical solution to this is to have multiple server names (cdn-a.example.com, cdn-b.example.com, ...) and round-robin requests to equivalent, alternative systems that serve the same image content.

Proposal:  Allow an `alternate` key that that has URI values, where each value is the full base URI ( host/prefix/identifier ) 

Thus, something like:
```
{
  "@context": "http://iiif.io/api/image/2/context.json",
  "@id": "http://a.example.org/prefix/id1234",
  "alternate": ["http://b.example.org/prefix/id1234", "http://a2.other.com/etc/someid"]
}
```

**Comment by acdha** [comment]
I'm not sure I see a compelling value of this for the narrow use-case mentioned: the current browser limits are high enough to hit diminishing returns due to connection setup overhead and TCP window scaling, and HTTP/2 solves that problem completely and is supported by a growing majority (currently just under 80%) of browsers:

http://caniuse.com/#feat=http2

The use-case which seems more compelling to me would be situations where the same content is available from multiple partner institutions or where institution maintains mirror copies on-site and through a non-profit/government/commercial hosting company, etc. and would like to indicate that relationship in case the main server is overloaded or offline.

**Comment by zimeon** [comment]
Discussion in eds call that the original use performance case and the mirror use case are incompatible and should not be supported via the same mechanism -- in the performance use case a client should immediately use the alternate locations in parellel, in the mirror use case a client should not use alternate use cases except in the case of an outage

**Comment by azaroth42** [comment]
Circulated to the list:  https://groups.google.com/forum/#!topic/iiif-discuss/ZeajqxsSB1g
Didn't include the link to the issue to try and centralize discussion on iiif-discuss rather than there.

**Comment by azaroth42** [comment]
Propose defer, lacking any feedback.

**Comment by zimeon** [comment]
Eds discussion: agree defer based on lack of feedback on [IIIF-Discuss post](https://groups.google.com/forum/#!topic/iiif-discuss/ZeajqxsSB1g)

**Comment by azaroth42** [comment]
Discussion at the Hague was that there is at least one implementation, but that the use case would be satisfied entirely by HTTP/2.  The interaction with Auth (different domains would potentially need different tokens) and HTTPS (would need wildcard certificates) is problematic.

Decision is close wontfix, and to add an implementation note encouraging adoption of HTTP/2 infrastructure.
