### ISSUE TITLE
Update size examples to include max

### ISSUE THREAD

**Issue by jpstroop** [IIIF/iiif.io#688]
Follow-on from #663. I don't have the files, and I'm not 100% sure we need to do this until after #678.

**Comment by azaroth42** [comment]
Not sure how we would represent it in the diagrams any differently from full.  A note in Example 1?

**Comment by jpstroop** [comment]
Me either, which is why I think we can probably skip it until full is gone.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by tomcrane** [comment]
The six examples in the [region](http://iiif.io/api/image/2.1/#region) section and the three in the [format](http://iiif.io/api/image/2.1/#format) section could use ```max``` instead of ```full``` in the size param slot, to encourage familiarity (otherwise all these examples employ deprecated syntax). Should we do this for every current use of size ```full```, apart from where it is a specific example of the now deprecated ```full``` size?

in some cases this would need an extra clarification, e.g., example 5:

region=125,15,200,200
.../125,15,200,200/full/0/default.jpg
**N.B. Returned image is 175,185 px**

The last point is only true if maxWidth and friends allow it - so maybe we state that for all the examples either no maxXXX is defined, or it's defined as something large so that the examples all work.

I can go through and make these changes if we want to do this, and push to mad_max branch.

**Comment by jpstroop** [comment]
Ah, for some reason I thought the parameters were part of the image. I'm happy to do this (and think we should) if the other @IIIF/editors agree.

**Comment by zimeon** [comment]
:+1: to changing `full` to `max` in all examples

**Comment by jpstroop** [comment]
OK, I've done this. Also added a note that this will change the canonical syntax in 3.0. See 

http://mad_max.iiif.io/api/image/2.1/#size

and

http://mad_max.iiif.io/api/image/2.1/#canonical-uri-syntax

**Comment by azaroth42** [comment]
Sorry, having seen it, I'm :-1: 

Now all the examples say max, but the canonical URI is still full. So what would OSD do?  Does it use max (though incompatible with 2.0, so no...) or full?  I think it thus needs to use full.
But ... a new client author would look at the examples and warnings and conclude that they should use max, not knowing that 2.0 servers won't work.

Can we change /some/ of the examples but not all, and remove the warning in canonical?

**Comment by jpstroop** [comment]
Changing some could work, but how do we know which?

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by zimeon** [comment]
See #687 where this was addressed
