### ISSUE TITLE
Move SHOULD NOT for initial int to Implementation Note

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif.io#732]
... in all classes for Presentation API. It doesn't really deserve to be normative in the spec for such a specific technology stack that would have trouble with it.

**Comment by zimeon** [comment]
This seems to be in three places:

[5.2. Sequence](http://iiif.io/api/presentation/2.1/#sequence)

> ... Names should begin with an alphabetical character. ...

[5.3. Canvas](http://iiif.io/api/presentation/2.1/#canvas)

> ... As with sequences, the name _SHOULD NOT_ begin with a number. ...

[5.5. Other Content Resources](http://iiif.io/api/presentation/2.1/#other-content-resources)

> ... As with other uses of the {name} parameter, it SHOULD NOT begin with a number. ...

I agree that this in non-normative, we still have valid RDF if the last URI segment begins with a number. However, because of the possible use of RDF/XML and other technologies based around QNames that have the [restriction that the local part must not start with a digit](https://www.w3.org/TR/xml/#NT-NameStartChar). I see two possible approaches:

  1. decide that we don't care, this isn't a problem with JSON-LD and various other RDF technologies. Hide the info in an implementation note
  2. accept that this will be an issue for some implementers using some RDF stacks and, while removing the _SHOULD NOT_, add a forward pointer to the implementation note. Could be something like: "It is recommended that names begin with an alphanumeric character, see [Implementation Notes](http://iiif.io/api/presentation/2.1/#c-implementation-notes)

Because this is an unfortunate gotcha that is easy to miss, I lean toward the second approach.

**Comment by azaroth42** [comment]
http://initial_int.iiif.io/api/presentation/2.1/#d-implementation-notes 
I think we would have heard about it from people if they'd run into it by now, so prefer option 1.

**Comment by jpstroop** [comment]
:+1:
