### ISSUE TITLE
Misleading @list designations in presentation API?

### ISSUE THREAD

**Issue by cubap** [IIIF/iiif.io#856]
> This can be floated to the discussion list, if desired, but it felt too `codey` and nitpicky for it.

### Current State of Issue
JSON-LD, in part, sought to [simplify lists](https://www.w3.org/TR/json-ld/#sets-and-lists). RDF lists were clumsy because the items had to be ordered with care, so most "lists" were considered unsorted by default, unless order was truly important. The Presentation API seems to have reversed that, with a few symptoms. There are 11 `@container`s listed in the [context file](http://iiif.io/api/presentation/2/context.json) as `@list`, the ordered array version of an `@set` that indicates order matters:

~~~~~
`members`      `sc:hasParts`
`collections`  `sc:hasCollections`
`manifests`    `sc:hasManifests`
`sequences`    `sc:hasSequences`
`canvases`     `sc:hasCanvases`
`resources`    `sc:hasAnnotations`
`images`       `sc:hasImageAnnotations`
`otherContent` `sc:hasLists`
`structures`   `sc:hasRanges`
`ranges`       `sc:hasRanges`
`metadata`     `sc:metadataLabels`
~~~~

### A Case for the Problem
We were making a table of contents and had a great set of `ranges` that described the proper order of `canvases` that were contributed out of order. The `sequences[n].canvases` array was a mess, as things were pushed onto the end of it as they were contributed. This is okay, because we were allowing the user to interact with the sequence and create groups, gatherings, chapters, etc. based on whatever physical, contextual, or content-related criteria she preferred. In fact, one `manifest` could support several of these orderings because a "top" `sc:Range` could be established to shepherd all the groups within it.

When we viewed the "Table of Contents" in Mirador, some ranges were in the right place, but some were not. The `ranges.children` property seemed to be based on the order of `structures` and not the internal order indicated. This is a side-concern for Mirador, but much more superficial. Not only can our special case be accommodated by manipulating the `manifest` to display different orders, if we wish, but we could also build a plugin for our "navigator" or "polyrangerator" if we wish. More significant was that Mirador was _not wrong_ to assume that `structures` was ordered because it was an `@list`.

### An Upsetting Proposal
Mirador—and so one assumes other applications—already assume that order matters in some of these properties for which it does not. This is not a problem when an unordered set is arbitrarily ordered, of course, because for display order is always imposed. However, when order matters and it is wrong, or a consistent order is presumed when it ought not be guaranteed, things break. I believe some of these contexts, in future versions, should be fixed, even though it is technically a breaking change, since `@set` is more general than `@list`. In important cases, the order can be imposed explicitly.

`canvases` and `metadata` should remain `@lists` since the proper display relies on knowing the order of these. `metadata` could be argued into a set, but since it is just labels for display and not a true and full cataloging of the object, it seems right to expect an order. Although `members` imitates other "hasPart" vocabularies, its role inside of a `sc:Range` may be seen as sequencing. I can imagine a structure (such as an index) that would not be dependant on order, but those may be better served in an `annotationList`.

All that remain should be changed to `@set`. `collections`, `manifests`, `sequences`, `resources`, `images`, and  `otherContent` are all clearly unordered sets within which order may be significant, but should be otherwise enforced if it is. In most cases, the consumer will be picking through these aggregations by type or generator to establish primacy for display. `structures` and `ranges` should importantly be `@set`s since they are carefully specified to be without order. `ranges` can overlap or share `canvas`es between them. The `viewingHint` and `startCanvas` properties reinforce the fragility of the arbitrary order of the array.

**Comment by cubap** [comment]
I can't tag these, but "presentation" would be a good one.

**Comment by tpendragon** [comment]
I'm not sure I parse this entirely, so I'm going to call out a few things I'm confused about.

> The ranges.children property seemed to be based on the order of structures and not the internal order indicated.

What's `ranges.children`, and what is the "internal order indicated" if not the order of structures? It seems to me like the use case is "display these top ranges in the order I gave them to you."

Regarding the items you're proposing be converted to set, there's a few I pretty strongly disagree with:

1. `collections` and `manifests` solve the Multi-Volume Work use case (now `members`). If one item has metadata and is composed of multiple sub-manifests, it's important that those manifests are in order. Volume 1 MUST be before Volume 2, and its order has to be a part of the list and it can't be trusted that you can sort by something like label.

2. `sequences` I think this is similar to my `structures` argument before - it seems reasonable and expected to me that the order I put my sequences in the JSON-LD is the order that they're rendered in the viewer. The only way to make that statement semantically is with an ordered list.


I think I agree that `resources`, `images`, and `otherContent` could be unordered, but I'm not sure what the use cases were for order when they came in.

> structures and ranges should importantly be @sets since they are carefully specified to be without order.

Can you point me to where these were specified as being without order? I'm definitely making the assumption that they are, right now, and `ranges` seems particularly important to be in order to make table of contents.

**Comment by azaroth42** [comment]
All of the list based properties should be lists for various reasons.  Whether Mirador correctly implements the specification or not is of no relevance to how the specification should be written ... that is a bug in Mirador, not the spec, if it does not do the right thing.

`collections` and `manifests` (and `members`) are ordered because, as Trey says, order is part of the concept of the collection structure. Especially for multi-volume works, but really for any collection.

`sequences` is important that it's ordered, otherwise it would break the rule that the _first_ sequence is embedded. If there were no order, then there would be no first sequence.  That the first and default sequence is embedded is important to reduce the number of interactions between client and server.

`resources` and `images` are the list of Annotations in an AnnotationList and the optimization to extract image annotations into the manifest directly.  Order is important here as we do not have z order indexing for images (and to do so would be a headache in a distributed environment that we'll cross when we have to for 3-D but hopefully not before) as well as for reading order of textual annotations.  So clients should render the resources annotated onto the canvases in the order specified in the lists.

`otherContent` ... okay, maybe this could be a set rather than an ordered list, but what's the rationale for changing it when systems already have to deal with lists for all other similar properties? If there's a requirement that comes up for processing annotation lists in order, then we have it covered. If we change it to a set, then we'd just have to revert back.

So I'm overall :-1: to the request without specific cases being stated for why order is a problem.

**Comment by cubap** [comment]
Okay, I get it. It is clear that there is what is probably a small bug in Mirador (and so can be handled there) that does not properly supercede the order within the `sc:Ranges` with the order of those sub-ranges in `structures`. As Trey was quick to see, the real trouble is in Mirador right now, which is where I should go back to.

Rob, I take your point that `collections` and `manifests` are ordered because often they are meant to be. In cases where the order needs to be explicitly unimplied, I can avoid using "collections" and just use another aggregation without breaking anything outright. As an example, we are working with the Tennyson family collection to represent the social evenings where a set of related manuscripts, books, and music would be placed on a communal table for perusal. Depending on the poetry being read, this collection would change, reusing some materials, but it is well-documented. The world doesn't end if this is not a `sc:Collection`, and so it may not be. The sort of recreation work we've been doing recently runs into this a lot, but IIIF is not wrong to prefer the GLAM cases for the standard. In Broken Books, which Bryan has demoed, I believe, the user groups (now `ranges`) the `canvases` into "leaves" (recto/verso) or may designate other special groups (quires, for example) that cannot be divided, but can be resituated into several different orders for presentation. It is just one more step to generate or alter a `sequence` of `canvases` to imitate the order of the assembled groups, so we ought not stretch the standard beyond its usefulness.

I don't think `sequences` breaks if you allow it to be a set and also require the first item to be embedded as the default, but I cannot think of a case where compelling an order on an intentionally unordered set causes an issue. Similarly, I disagree that `resources` and `images` have to be ordered. A z-indexed list of images feels like a special resource that would follow certain expected rules (including sequence), just as a spectral or RTI image set would. The generic cases doesn't seem to require it, but I have not encountered a breaking case yet.

Thanks for the time on this. I am happy to be deep enough into this to be hitting these issues and I respect the standard where it is at. I'll close this up.

**Comment by azaroth42** [comment]
@cubap, Is there a problem with the Tennyson example and collections/manifests being ordered? If so, I'm afraid that I don't understand it. My view is that if order isn't important, then the fact that there is one is also unimportant :)  

I agree though that resources, images, otherContent and sequences don't _require_ order in all situations, but as there are some situations when the order is useful to maintain (combined with above that if it's not important, then it doesn't hurt to have one), it's better to consistently require it across the board. 

If there's a use case for different application behavior, we could discuss (in a separate issue) a viewingHint or similar that might trigger that behavior?

**Comment by cubap** [comment]
There is a distributed problem, not a local one. Our application will obviously ignore the order, but other consumers of the manifests may not know that is the case. The bug in Mirador is an artifact of assuming that because `@list` means order _matters_ that is also means order is intentional and maybe even more important than other ordering principles, which we intend to supercede. I will always yield to convention, but I am cautious of it.

Philosophically, I don't like encoding things in ways that imply more structure than is intended, even if it is always expected to be asymptomatic. A lot of the misuse of TEI that I have seen is from using extensions that look like they should fit, but do not. Semantics is really tricky in our developer-researcher conversations because `oa:Annotation` is not an "annotation" as scholars see it, but so many letters overlap. 

A simple example in real life is a grocery list. It is _probably_ an `@set` with all items included, but the order not important. It _may_ be an `@list` if you have organized it for efficient travel through the store, or by anticipated price, or by alphabet. If it is an `@list`, that additional information should be included alongside the ordering principle itself. The same would be expected if I had the items subgrouped by department or store. Now, if I gave someone a grocery set and they thought it was a grocery list, it may not break their trip, but it may be much less efficient as they crisscross the county and go back to the same store for the next purchase. If they assume a list is ordered by their local convention (prioritization of alternatives) and I offer the list assuming they know my local convention (say alphabetically), I may not even get all my groceries.

We've talked about viewingHint already and plan to implement it for the plugin we'll build for the Mirador "polyrangerator" (or whatever—I find stupid names motivate more careful design). It is a good solution. I acknowledge it is a personal principle to use properties like this for constraint or clarification, not to invert or undo. That said, it's a good standard and I understand the value in just picking a side and accommodating the outliers as needed. I'm not converted, but I am convinced.
