### ISSUE TITLE
include showcase items in "Apps & Demos"

### ISSUE THREAD

**Issue by kshawkin** [IIIF/iiif.io#890]
There are a few things included http://showcase.iiif.io/ that are not also listed at http://iiif.io/apps-demos/ , but I'd suggest including all at http://iiif.io/apps-demos/ so that there's a single complete list.  That way http://showcase.iiif.io/ would truly be a "showcase" for the best cases.

**Comment by azaroth42** [comment]
This was always the intent, we just haven't done it yet :)

**Comment by kshawkin** [comment]
Excellent. I realize that you're waiting on Sheila to start her new job, but if you're able to make this change by the end of the week, I can update the wording at http://www.ultraslavonic.info/talks/20160824.html before I print this to say that everything is in http://iiif.io/apps-demos/ , with highlights in http://showcase.iiif.io/ .

**Comment by azaroth42** [comment]
I doubt if it will be this week, sorry! We need to get some better infrastructure in place so that different people can manage different parts of the site. And then there was been some discussion about bigger changes to the layout. apps-demos might end up redirecting to showcase or vice versa, we're not sure yet :)

**Comment by tomcrane** [comment]
Moved to https://github.com/IIIF/iiif-root-website/issues/18
